include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
use anyhow::Result;
use std::ffi::CString;
/// Minimal perfect hash structure wrapping the C implementation.
/// The actual structure is generated by bindgen.
impl mph {
    pub fn load(path: &str) -> Result<Self> {
        unsafe {
            load_mph(CString::new(path)?.as_c_str().as_ptr() as *const u8)
                .as_ref()
                .map(|m| *m)
                .ok_or(anyhow::anyhow!("Cannot load MPH"))
        }
    }

    pub fn get(&self, key: &str) -> usize {
        unsafe { mph_get_byte_array(self, key.as_ptr(), key.len() as u64) as usize }
    }

    pub fn size(&self) -> usize {
        self.size as usize
    }
}
